# Generated by Django 6.0 on 2025-12-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_profile', '0002_alter_usercontext_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontext',
            name='context',
            field=models.JSONField(),
        ),
    ]
