# Generated by Django 6.0 on 2026-02-05 12:38

import hashlib
import json

from django.db import migrations, models


def _compute_context_hash(value):
    if isinstance(value, str):
        data = value.encode("utf-8")
    else:
        data = json.dumps(value, sort_keys=True).encode("utf-8")
    return hashlib.sha256(data).hexdigest()


def backfill_context_hash(apps, schema_editor):
    UserContext = apps.get_model("applicant_profile", "UserContext")
    for row in UserContext.objects.all():
        if row.context is not None:
            row.context_hash = _compute_context_hash(row.context)
            row.save(update_fields=["context_hash"])
    # Remove duplicate (user, context_hash): keep row with smallest id per group
    from django.db.models import Min

    keep_ids = (
        UserContext.objects.values("user_id", "context_hash")
        .annotate(min_id=Min("id"))
        .values_list("min_id", flat=True)
    )
    UserContext.objects.exclude(id__in=keep_ids).filter(
        context_hash__isnull=False
    ).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("applicant_profile", "0003_alter_usercontext_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="context_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.RunPython(backfill_context_hash, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="usercontext",
            constraint=models.UniqueConstraint(
                fields=("user", "context_hash"), name="unique_context_per_user"
            ),
        ),
    ]
