# Generated by Django 6.0 on 2026-02-05 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant_profile", "0004_add_context_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usercontext",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_name_per_user"
            ),
        ),
    ]
