# Generated by Django 6.0 on 2026-02-06 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applicant_profile", "0005_usercontext_unique_name_per_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usercontext",
            name="unique_context_per_user",
        ),
    ]
