# Generated by Django 6.0 on 2026-02-06 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant_profile", "0006_remove_usercontext_unique_context_per_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usercontext",
            constraint=models.UniqueConstraint(
                fields=("user", "context_hash"), name="unique_context_per_user"
            ),
        ),
    ]
