"""
Django settings for resume_builder project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
import environ

# Set library path for WeasyPrint on macOS
if sys.platform == "darwin":
    homebrew_paths = ["/opt/homebrew/lib", "/usr/local/lib"]
    for lib_path in homebrew_paths:
        if os.path.exists(lib_path):
            current_path = os.environ.get("DYLD_FALLBACK_LIBRARY_PATH", "")
            if lib_path not in current_path:
                os.environ["DYLD_FALLBACK_LIBRARY_PATH"] = (
                    f"{lib_path}:{current_path}" if current_path else lib_path
                )
            break


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

local_env = BASE_DIR / ".env"
if local_env.exists():
    environ.Env.read_env(local_env)

FRONTEND_DOMAIN = env.str("FRONTEND_DOMAIN", "http://localhost:3000")
OPENAI_API_KEY = env.str("OPENAI_API_KEY", "")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    "SECRET_KEY", "django-insecure-r1&!0o!v%&y1-2h0*$e%&46(jcxr3k7vdzu7k2yxf^um0e=^8a"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["0.0.0.0", "localhost", "127.0.0.1"])

CORS_ALLOWED_ORIGINS = [FRONTEND_DOMAIN, "http://localhost:3000"]
CORS_ALLOW_CREDENTIALS = True  # Required for JWT cookies

CSRF_TRUSTED_ORIGINS = [FRONTEND_DOMAIN, "http://localhost:3000"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #
    "corsheaders",
    "django.contrib.sites",
    # account
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    # rest framework
    "rest_framework",
    "rest_framework_simplejwt",  # redundant?
    "rest_framework_simplejwt.token_blacklist",  # JWT blacklist
    "rest_framework.authtoken",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    # apps
    "accounts",
    "applicant_profile",
    "job_profile",
    "ai_generation",
    # third party
    "drf_spectacular",
]

# for allauth
SITE_ID = 1

# rest framework (use jwt as default)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# for dj-rest-auth
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE_USE_CSRF": True,
    "JWT_AUTH_HTTPONLY": True,
    # correct?
    "JWT_AUTH_SAMESITE": env.str(
        "JWT_AUTH_SAMESITE", "Lax"
    ),  # keep lax if domains match, else none
    "JWT_AUTH_SECURE": not DEBUG,
    "JWT_AUTH_COOKIE": "access_token",
    "JWT_AUTH_REFRESH_COOKIE": "refresh_token",
    "REGISTER_SERIALIZER": "accounts.serializers.CustomRegisterSerializer",
    "SESSION_LOGIN": False,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Resume Builder API",
    "DESCRIPTION": "API documentation for Resume Builder application",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "AUTHENTICATION_WHITELIST": [
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ],
}

# allauth config
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_ADAPTER = "accounts.adapters.CustomAccountAdapter"
ACCOUNT_DEFAULT_HTTP_PROTOCOL = env.str("HTTP_PROTOCOL", "http")

# ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = env.str("EMAIL_REDIRECT")
# ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = env.str("EMAIL_REDIRECT")


ACCOUNT_PASSWORD_RESET_EXPIRE_DAYS = 1


EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # allauth
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "resume_builder.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# for allauth - how are users authenticated
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

WSGI_APPLICATION = "resume_builder.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_url = env.str("DATABASE_URL", default=None)
if db_url:
    db_config = dj_database_url.parse(db_url, conn_max_age=600)
    db_config["OPTIONS"] = {
        "sslmode": "require",
    }
    DATABASES = {
        "default": db_config,
    }
else:
    # Default to PostgreSQL
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env.str("POSTGRES_DB", default="resume_builder"),
            "USER": env.str("POSTGRES_USER", default="postgres"),
            "PASSWORD": env.str("POSTGRES_PASSWORD", default="postgres"),
            "HOST": env.str("DB_HOST", default="127.0.0.1"),
            "PORT": env.str("DB_PORT", default="5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
