# Generated by Django 6.0 on 2026-02-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_generation", "0002_remove_documentversion_version_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="context_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "context_hash"),
                name="unique_context_hash_per_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "version_name"),
                name="unique_version_name_per_document",
            ),
        ),
    ]
