# Generated by Django 6.0 on 2026-02-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_generation", "0003_add_documentversion_context_hash"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentversion",
            name="unique_context_hash_per_document",
        ),
        migrations.RemoveConstraint(
            model_name="documentversion",
            name="unique_version_name_per_document",
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "context_hash", "version_name"),
                name="unique_version_document_per_document",
            ),
        ),
    ]
