# Generated by Django 6.0 on 2026-02-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ai_generation",
            "0004_remove_documentversion_unique_context_hash_per_document_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
