# Generated by Django 6.0 on 2026-02-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_generation", "0005_documentversion_updated_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentversion",
            name="unique_version_document_per_document",
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "version_name"), name="unique_name_per_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "context_hash"), name="unique_markdown_per_document"
            ),
        ),
    ]
