# Generated by Django 6.0 on 2026-02-12 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_generation", "0007_ensure_documentversion_updated_at"),
        ("applicant_profile", "0007_usercontext_unique_context_per_user"),
        ("job_profile", "0003_alter_jobdescription_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="document",
            name="unique_job_per_user",
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("user", "user_context", "job_description", "document_type"),
                name="unique_document_type_per_user_context_and_job_description",
            ),
        ),
    ]
